// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Domain.SerialNumber", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SerialKey")
                        .HasColumnType("int");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SerialNumbers");

                    b.HasData(
                        new
                        {
                            Id = "3b087e43-b121-44ca-90e4-40bc63802ca6",
                            SerialKey = 724503,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "53ceaddd-13dc-4b4b-9506-48074ae27b5c",
                            SerialKey = 856872,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "4a6a4c87-31c7-40c3-a1b9-5691e65fe437",
                            SerialKey = 307196,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "fffae6ee-12ba-4442-917f-32bc2bc7648c",
                            SerialKey = 262356,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "c14fec24-0442-4010-8670-4bec6c4cb4ab",
                            SerialKey = 305147,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "70c782cc-8d57-424e-820d-aa02c556a2af",
                            SerialKey = 129505,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "735018d9-42dc-4578-9b22-c81ea50da274",
                            SerialKey = 751204,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "782a35be-ae75-477b-ab1d-361dd9d601be",
                            SerialKey = 293324,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "3e858001-b483-4ae2-881b-86af4e4fa661",
                            SerialKey = 186420,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "1d3d1ec7-c65e-455c-92dd-fbfaae9917ba",
                            SerialKey = 517665,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "a8dcfce4-538f-472e-b5ce-1a3ce5696f55",
                            SerialKey = 526293,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "678c5118-8f10-4b04-a745-bb2ec78445d9",
                            SerialKey = 223212,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "84e3208b-dea0-48f4-af2c-7333c944aa15",
                            SerialKey = 513575,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "a3d105ec-13e7-488b-9fce-6a1f42f82d58",
                            SerialKey = 782235,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "e0377c56-d74d-4975-9424-e162ef4c3e51",
                            SerialKey = 238047,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "4062c9a0-4b09-4965-a49e-7849633ffd5f",
                            SerialKey = 883708,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "e47a9d27-fbba-4549-b7ff-f426e9666f16",
                            SerialKey = 586554,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "f91f9b76-72f6-4f14-8435-993581d091ab",
                            SerialKey = 102717,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "37c7ecbf-ec51-434d-929a-854f8aebe797",
                            SerialKey = 924936,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "0128f5f8-49b1-4bc9-9e30-d723d1dd43d2",
                            SerialKey = 566660,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "c9ca1b7c-b429-4ea6-8fe2-36e3af715dc4",
                            SerialKey = 991742,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "e7698a27-9921-4e02-982b-a17833339335",
                            SerialKey = 803146,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "66952d51-b8e1-45b7-abd7-f5d71641de6e",
                            SerialKey = 640796,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "1106b082-d851-464b-97ed-6937f8ea07d6",
                            SerialKey = 873090,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "554f135f-cc97-46a4-aa27-ff7ec6150519",
                            SerialKey = 571863,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "ae3f257a-4219-4414-a5ce-50bc84aba4c4",
                            SerialKey = 186572,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "48fe2145-fa30-4bda-aafc-369fc2d4fdba",
                            SerialKey = 633942,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "d8839100-2592-4c1a-9fba-d03fdd940425",
                            SerialKey = 691068,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "5c194c97-4e79-40e0-88d3-178b1d5f6486",
                            SerialKey = 234675,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "727c8c73-fa44-4084-a3f4-095e11d79854",
                            SerialKey = 595452,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "04c13716-9661-4ff1-bfb1-62dec2ecf6d5",
                            SerialKey = 426706,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "9c24fe43-08b7-423c-ae37-65c8431abd7e",
                            SerialKey = 968859,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "7951d0f0-9084-4274-a26a-d02435d08f62",
                            SerialKey = 768508,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "ba7780e8-03b5-4177-ab9d-a4c96cb8420f",
                            SerialKey = 511264,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "abd119b5-be72-4a01-aa3f-85bcb79c71ad",
                            SerialKey = 188827,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "ccf90fac-708a-49f6-a4fc-33484ccb9c95",
                            SerialKey = 462715,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "f1d88c76-4b60-4260-8d73-823255b2f7b8",
                            SerialKey = 213996,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "c0142edd-46fd-4391-9371-c1a5f1b30d21",
                            SerialKey = 860760,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "e8c6cb9b-9bcc-4c72-988f-c77d560cc81b",
                            SerialKey = 360480,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "d3183187-d51d-49e1-b61e-0f05a2975bc8",
                            SerialKey = 642059,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "1272de4f-dd79-405d-88b0-e53563a6512e",
                            SerialKey = 616097,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "60e91dc0-6d72-49d5-bf1c-6255e0bc63a4",
                            SerialKey = 457269,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "31932592-8ac8-429e-8c52-65d7736a0060",
                            SerialKey = 492855,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "d21fedf4-58d8-4e91-becc-c06249e79bf9",
                            SerialKey = 410075,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "90617c2e-bb91-41d7-bd74-ded790e11f81",
                            SerialKey = 685503,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "fb60b3cc-8bc0-4a69-aae5-cc749c62d4f1",
                            SerialKey = 965948,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "15f0748d-06ab-45af-9bcb-2d2174a8c1e9",
                            SerialKey = 835974,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "e11e842e-3d46-44b6-8634-d204e5eae171",
                            SerialKey = 498754,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "18999856-e902-445b-b57e-190ae61ac4a5",
                            SerialKey = 857721,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "e91a98cf-b864-47b0-b9a1-9f26dcbcb64e",
                            SerialKey = 305473,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "e0141255-26d8-43cc-bdea-255d4fc8fdc6",
                            SerialKey = 235828,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "5fbe64d7-a27b-4b20-af54-8a5065410c4f",
                            SerialKey = 844550,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "8c47b230-ba54-4fb8-9f9e-7317974d4672",
                            SerialKey = 443369,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "fbc4c75b-2df1-4492-b92b-6acbeb234547",
                            SerialKey = 170468,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "9777d31f-5d02-440d-b281-1620f42a0628",
                            SerialKey = 157496,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "10340a1d-3f3e-4397-9f1e-04087374dda4",
                            SerialKey = 921356,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "389a81e2-e770-4685-a0ec-f18b29004942",
                            SerialKey = 316075,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "501bbde5-be3f-4041-a68c-a1da03c47652",
                            SerialKey = 434104,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "deb53225-3a15-4eba-8348-030c81f41683",
                            SerialKey = 690491,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "8666be3e-01e2-4f0a-bd86-a0e6771b6b0b",
                            SerialKey = 218574,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "096b4b16-65c3-4d83-858f-dfe781d8c01b",
                            SerialKey = 495562,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "a65f1759-6a7f-4b57-b176-4d5ef496385e",
                            SerialKey = 160135,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "624786f6-013f-4bbd-a2a5-7a39c61e15a8",
                            SerialKey = 158648,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "42aa6288-294d-46c3-a870-da28131857d4",
                            SerialKey = 590966,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "7ff3ac81-1520-46e9-99f3-a826650d364d",
                            SerialKey = 190959,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "3fd02a40-7206-4208-b69d-7be64e2e0a2e",
                            SerialKey = 557433,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "10da9b45-7f20-465b-9ae3-397e48c4c4b8",
                            SerialKey = 454703,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "6a691ebd-699e-4a07-b79a-0c265f582933",
                            SerialKey = 102311,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "09e78033-c91b-46a7-b5aa-f3bd85698dee",
                            SerialKey = 693408,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "9d7d53f5-03b2-4135-a2eb-26f7c1fdbafd",
                            SerialKey = 775330,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "283ec2c1-3d76-4268-83cd-fd3ce9088b49",
                            SerialKey = 769711,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "c3feced5-9843-43b0-a808-367273e0de49",
                            SerialKey = 725793,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "14001f17-064a-4ca0-8d3e-acb68e8d08d8",
                            SerialKey = 742236,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "f95d3e62-913d-4283-a501-6aab98dffaa6",
                            SerialKey = 382876,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "eadea6de-2db5-43d7-8cb5-ac8a2934b816",
                            SerialKey = 950561,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "6e755887-d01e-4371-9621-294976ee8a20",
                            SerialKey = 634472,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "be806f7b-5969-4a5c-8a94-dabd007413e4",
                            SerialKey = 410291,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "7e4def2c-887a-411c-874d-0a089462fbd0",
                            SerialKey = 330720,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "e4d4ff88-40c5-46bb-96fc-a2c36351bb9d",
                            SerialKey = 287587,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "b52bf386-bfee-43ae-83af-1e6203c47c59",
                            SerialKey = 605913,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "47b06a39-7d41-476a-af43-f92ca79d25b6",
                            SerialKey = 350597,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "5a24c4de-7fbc-4e32-8b59-2abd3d9bbedd",
                            SerialKey = 235187,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "f352bf7c-d0e5-46f2-86ed-dd86740a4af6",
                            SerialKey = 833345,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "d7b11994-f713-417f-ba72-01ea2279d4fe",
                            SerialKey = 929201,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "6bde6b4b-e1b2-42a1-8fdf-4bbfaa57a5bf",
                            SerialKey = 459624,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "066088e0-68fa-411e-b562-257d12445896",
                            SerialKey = 582154,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "eb4a84af-ce3a-4eb5-8b25-a40795a9b1ca",
                            SerialKey = 625490,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "b1eb522b-f670-4c1a-9e19-5aa9cb57d575",
                            SerialKey = 698040,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "ade7e430-94d7-4466-b9cd-731fc5ecc6f6",
                            SerialKey = 453767,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "f6d58432-f91f-4fec-b6b1-59efc4ab9dc9",
                            SerialKey = 267469,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "51317fa2-25b2-436f-8947-c9ff8ceb3aeb",
                            SerialKey = 246640,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "cfa7bc89-4254-4d54-938a-83e8a778c3b9",
                            SerialKey = 779891,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "7f653dc4-f9cf-46ac-a514-54e532d68cca",
                            SerialKey = 270268,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "b6d67b96-edb8-478d-b025-5bcccb4c0cf2",
                            SerialKey = 241905,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "c4556e53-75fc-4ce8-932d-67b7ac47ca48",
                            SerialKey = 246496,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "ac578fa9-6ee9-49fc-a546-2c632df29ff2",
                            SerialKey = 555961,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "9818ec31-70f2-4178-86b4-56ddef3fb114",
                            SerialKey = 398621,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "957a8521-9164-47a0-b984-311482cd79da",
                            SerialKey = 901887,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "310ee8d4-b2aa-4d6c-807d-6a55e93afaf6",
                            SerialKey = 319115,
                            TimesUsed = 0
                        },
                        new
                        {
                            Id = "40eb73c2-5613-454a-9bb7-4c241a9b1581",
                            SerialKey = 228070,
                            TimesUsed = 0
                        });
                });

            modelBuilder.Entity("Domain.Submission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
